// <auto-generated />
using System;
using InspireEduCRM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InspireEduCRM.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260619185633_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerServiceRepId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FollowUpDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FollowUpType")
                        .HasColumnType("int");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("NextAction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerServiceRepId");

                    b.HasIndex("LeadId");

                    b.ToTable("FollowUps");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId")
                        .IsUnique();

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrincipalMobile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrincipalName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<int>("InterestLevel")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SalesRepId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("SalesRepId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.VisitBook", b =>
                {
                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("VisitId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("VisitBooks");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.Contact", b =>
                {
                    b.HasOne("InspireEduCRM.Domain.Entities.School", "School")
                        .WithMany("Contacts")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.FollowUp", b =>
                {
                    b.HasOne("InspireEduCRM.Domain.Entities.Contact", "Contact")
                        .WithMany("FollowUps")
                        .HasForeignKey("ContactId");

                    b.HasOne("InspireEduCRM.Domain.Entities.User", "CustomerServiceRep")
                        .WithMany("FollowUps")
                        .HasForeignKey("CustomerServiceRepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InspireEduCRM.Domain.Entities.Lead", "Lead")
                        .WithMany("FollowUps")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("CustomerServiceRep");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.Lead", b =>
                {
                    b.HasOne("InspireEduCRM.Domain.Entities.School", "School")
                        .WithOne("Lead")
                        .HasForeignKey("InspireEduCRM.Domain.Entities.Lead", "SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.Visit", b =>
                {
                    b.HasOne("InspireEduCRM.Domain.Entities.Contact", "Contact")
                        .WithMany("Visits")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspireEduCRM.Domain.Entities.User", "SalesRep")
                        .WithMany("Visits")
                        .HasForeignKey("SalesRepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InspireEduCRM.Domain.Entities.School", "School")
                        .WithMany("Visits")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("SalesRep");

                    b.Navigation("School");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.VisitBook", b =>
                {
                    b.HasOne("InspireEduCRM.Domain.Entities.Book", "Book")
                        .WithMany("VisitBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspireEduCRM.Domain.Entities.Visit", "Visit")
                        .WithMany("VisitBooks")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.Book", b =>
                {
                    b.Navigation("VisitBooks");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.Contact", b =>
                {
                    b.Navigation("FollowUps");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.Lead", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.School", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Lead");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.User", b =>
                {
                    b.Navigation("FollowUps");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("InspireEduCRM.Domain.Entities.Visit", b =>
                {
                    b.Navigation("VisitBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
